# This is a config for E2B sandbox template.
# You can use template ID (epp54kwvgfxl46ib3ybq) or template name (prompt-base-v0) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox.create("prompt-base-v0") # Sync sandbox
# sandbox = await AsyncSandbox.create("prompt-base-v0") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('prompt-base-v0')

team_id = "e72fd847-eb5c-490e-bccf-a8e8560554fa"
start_cmd = "/compile_page.sh"
dockerfile = "e2b.Dockerfile"
template_name = "prompt-base-v0"
template_id = "epp54kwvgfxl46ib3ybq"
